UniversalMediaServer/api

- package.json
- yarn.lock
> Update to latest stuff

- .travis.yml
- package.json
Reverts UniversalMediaServer/api#52
> Revert "use latest yarn 1"

- src/controllers/media.ts
- src/models/FailedLookups.ts
- src/models/MediaMetadata.ts
- src/routes/media.ts
- test/e2e/media.spec.ts
- test/unit/media.spec.ts
- tsconfig.json
This is the e2e working but just need guidance on what we want to store & return for this
> search by title e2e

- .gitignore
- README.md
- ecosystem.config.js
- package.json
- src/controllers/media.ts
- src/cron/all-episodes.ts
- src/models/EpisodeProcessing.ts
- src/models/FailedLookups.ts
- src/models/MediaMetadata.ts
- src/models/connection.ts
- src/utils/data-mapper.ts
- test/e2e/all-episodes-cron.spec.ts
- test/e2e/media.spec.ts
- test/mocks.js
- test/models/FailedLookups.spec.ts
- test/models/MovieMetadata.spec.ts
- test/unit/data-mapper.spec.ts
- yarn.lock
depends on https://github.com/UniversalMediaServer/api/pull/76 first
> precache all episodes in a series

- package.json
- src/controllers/media.ts
- yarn.lock
Fixes episode season numbers. Can revert to NPM package once the library fix has been merged and released to NPM.
Library PR for reference https://github.com/worr/node-imdb-api/pull/73
> fix episode numbers

- package.json
- src/app.ts
- test/e2e/media.spec.ts
- yarn.lock
This module adds extra logic to node's httpserver stop, where it also clears up all open connections before closing the server, this gets rid of one of the jest errors
> fix one leak

- src/models/MediaMetadata.ts
- src/models/SeriesMetadata.ts
> do not expire metadata records once saved

- src/app.ts
https://github.com/UniversalMediaServer/api/issues/134
> BUGFIX send errors to stderr

- src/services/imdb-api.ts
- src/services/opensubtitles.ts
realised we need to throw these so the promise isnt fufilled with null
> throw errors

- package.json
- src/controllers/media.ts
- src/services/imdb-api.ts
- yarn.lock
I havent been able to test this with a paid key
https://github.com/UniversalMediaServer/node-imdb-api/pull/2/files
> allow use of private omdb server

- src/app.ts
- src/controllers/media.ts
- src/helpers/customErrors.ts
I'm interested in your thoughts about this @js-kyle because it exposes a particular inner working of the server to the client which might not be something we want to do. The other option is to throw our existing `MediaNotFoundError`
> Throw IMDbIDNotFoundError if we can't figure out the IMDb ID

- src/app.ts
- src/controllers/media.ts
- src/utils/data-mapper.ts
- test/unit/data-mapper.spec.ts
https://github.com/UniversalMediaServer/api/issues/197
https://github.com/UniversalMediaServer/api/issues/196
https://github.com/UniversalMediaServer/api/issues/166
> Some progress for client alpha release

- src/controllers/media.ts
- src/models/FailedLookups.ts
- test/e2e/media.spec.ts
https://github.com/UniversalMediaServer/api/issues/190
> Validate Open Subs responses for osdbhash endpoint

- src/controllers/media.ts
> Only look for TV series in TV series lookup route

- package.json
- yarn.lock
These are both major version changes
> Bump jest and ts-jest

- package.json
- src/controllers/media.ts
- src/models/MediaMetadata.ts
- src/services/imdb-api.ts
- src/utils/data-mapper.ts
- test/mocks.js
- yarn.lock
They fixed that season bug and added the ability to use the private Patreon server, was that everything we customized @js-kyle ?
> Use imdb-api instead of our fork

- src/controllers/media.ts
- src/cron/all-episodes.ts
- src/models/FailedLookups.ts
> Fixed imdbid not in schema error

- src/controllers/media.ts
- src/models/SeriesMetadata.ts
- src/models/connection.ts
- test/e2e/media.spec.ts
See commit messages, mostly commenting
> Minor updates

- src/utils/data-mapper.ts
- test/unit/data-mapper.spec.ts
> Filter out undefined, null and NaN values

- .github/workflows/ci.yaml
- package.json
- src/controllers/media.ts
https://github.com/UniversalMediaServer/api/issues/430
> run tsc on ci

- src/models/FailedLookups.ts
- src/models/MediaMetadata.ts
- test/e2e/media.spec.ts
- test/models/FailedLookups.spec.ts
We should also probably have compound indexes for combinations of these, but this is a start
> Added indexes for year, season and episode

- .github/workflows/ci.yaml
Fix is from https://github.com/dependabot/dependabot-core/issues/3253#issuecomment-841656411
> Fix dependabot secrets

- src/controllers/media.ts
- src/services/external-api-helper.ts
> Move on to OMDb search if Open Subtitles is offline

- src/controllers/media.ts
- test/e2e/media-video.spec.ts
> Fix failed search when there is already a stored result with the same IMDb ID

- src/models/SeriesMetadata.ts
- yarn.lock
It possibly could be unique if we had searchMatches for it, but I can think of cases where it still wouldn't be, like the titles of anime series where you might want to have a Japanese title and an English (and other languages) translated title.
This logic possibly also applies to media entries so we should maybe consider making the same change.
> 560 series dupes

- .github/workflows/ci.yaml
- package.json
- yarn.lock
See https://github.com/Automattic/mongoose/issues/10415#issuecomment-878651581
> Fix mongoose incompatibility with @types/node@16

- src/models/SeriesMetadata.ts
Not sure if this will fix it but worth a try
> Try to fix NaN #595

- package.json
- yarn.lock
Reverts UniversalMediaServer/api#582
> Revert "Bump mongodb-memory-server from 6.9.6 to 7.2.0"

- .github/workflows/ci.yaml
- package.json
- src/controllers/info.ts
- src/controllers/media.ts
- src/helpers/subversioning.ts
- src/models/FailedLookups.ts
- src/models/MediaMetadata.ts
- src/models/SeasonMetadata.ts
- src/models/SeriesMetadata.ts
- src/models/TMDBConfiguration.ts
- src/routes/index.ts
- src/routes/media.ts
- src/services/external-api-helper.ts
- src/services/omdb-api.ts
- src/services/tmdb-api.ts
- src/utils/data-mapper.ts
- test/e2e/info.spec.ts
- test/e2e/media-video.spec.ts
- test/e2e/media.deprecated.spec.ts
- test/e2e/media.spec.ts
- test/unit/data-mapper.spec.ts
- yarn.lock
> TMDB integration

- src/utils/data-mapper.ts
- test/unit/data-mapper.spec.ts
> Add series type to series

- package.json
- src/models/connection.ts
- test/e2e/info.spec.ts
- test/e2e/media-video.spec.ts
- test/e2e/media.deprecated.spec.ts
- test/e2e/media.spec.ts
- test/models/FailedLookups.spec.ts
- test/models/MediaMetadata.spec.ts
- yarn.lock
Reverts UniversalMediaServer/api#685
> Revert "mongoose 6 minor changes"

- package.json
- yarn.lock
Reverts UniversalMediaServer/api#794
> Revert "Bump eslint from 7.32.0 to 8.7.0"

- src/helpers/subversioning.ts
This is a followup from #866 because it will lead to more episode matches
> Bump video subversion

- ecosystem.config.js
This should reduce some memory usage as we don't need type checking in prod
> transpileOnly mode in prod

- package.json
- src/routes/index.ts
- yarn.lock
adds a private endpoint to initiate creation of a memory snapshot for later debugging
> add heapdump endpoint

- src/controllers/media.ts
- src/models/MediaMetadata.ts
> More database performance improvements

- package.json
- src/app.ts
- src/tracing.ts
- yarn.lock
Adds [opentelemetry](https://opentelemetry.io/) standard metrics extraction
> feat: opentelemetry

- src/controllers/media.ts
- src/services/external-api-helper.ts
- test/e2e/media-localize.spec.ts
TMDB supports lowercase versions so this was easy
Fixes https://github.com/UniversalMediaServer/UniversalMediaServer/issues/5191
> Fixed API error for languages with locales, like pt-br and en-gb
